services:
  - type: web
    name: personal-finance-bi-dashboard
    env: node
    plan: free
    buildCommand: ""
    startCommand: npm start
    envVars:
      - key: DASHBOARD_USER
        sync: false
      - key: DASHBOARD_PASSWORD
        sync: false
      - key: GOOGLE_CSV_URL
        value: https://docs.google.com/spreadsheets/d/1TzNIHcOvIC4uhMi2rqJ9xP1kRFco7c4OKhxE5Woylro/gviz/tq?tqx=out:csv&gid=504817751
      - key: EXCHANGE_RATE_URL
        value: https://open.er-api.com/v6/latest/USD
